/*
 * Tpay.com Technical Documentation
 *
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"bda5eda723bf1ae71a82e90a249803d3f852248d\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: pt@tpay.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CreateFields
    /// </summary>
    [DataContract]
    public partial class CreateFields :  IEquatable<CreateFields>, IValidatableObject
    {
        /// <summary>
        /// Customer language
        /// </summary>
        /// <value>Customer language</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LanguageEnum
        {
            /// <summary>
            /// Enum Pl for value: pl
            /// </summary>
            [EnumMember(Value = "pl")]
            Pl = 1,

            /// <summary>
            /// Enum En for value: en
            /// </summary>
            [EnumMember(Value = "en")]
            En = 2,

            /// <summary>
            /// Enum De for value: de
            /// </summary>
            [EnumMember(Value = "de")]
            De = 3

        }

        /// <summary>
        /// Customer language
        /// </summary>
        /// <value>Customer language</value>
        [DataMember(Name="language", EmitDefaultValue=false)]
        public LanguageEnum? Language { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateFields" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateFields() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateFields" /> class.
        /// </summary>
        /// <param name="id">Merchant ID in Tpay.com system (required).</param>
        /// <param name="amount">Transaction amount. Please always send the amount with two decimal places like 10.00 (required).</param>
        /// <param name="description">Transaction description (required).</param>
        /// <param name="crc">Auxiliary parameter to identify the transaction on the merchant side. We do recommend to encode your crc value in base64. The exact value of crc used to create transaction will be returned in tpay payment notification as tr_crc parameter..</param>
        /// <param name="md5sum">md5 sum calculated from id.&#39;&amp;&#39;.amount.&#39;&amp;&#39;.crc.&#39;&amp;&#39;.security_code where dots means concatenation (security code can be found in merchant panel). (required).</param>
        /// <param name="group">Transaction group number see the \&quot;id\&quot; element in https://secure.tpay.com/groups-{id}0.js . For example https://secure.tpay.com/groups-10100.js or https://secure.tpay.com/groups-10100.js?json (required).</param>
        /// <param name="resultUrl">Merchant endpoint for payment notification.</param>
        /// <param name="resultEmail">Email address where notification after payment will be sent (overrides defined in merchant panel). You can add more addresses by comma concatenation..</param>
        /// <param name="merchantDescription">Name of merchant displayed in transaction panel (overrides defined in merchant panel).</param>
        /// <param name="customDescription">Additional info to be displayed in transaction panel (overrides defined in merchant panel).</param>
        /// <param name="returnUrl">url to redirect customer in case of payment success.</param>
        /// <param name="returnErrorUrl">url to redirect customer in case of payment failure.</param>
        /// <param name="language">Customer language (default to LanguageEnum.Pl).</param>
        /// <param name="email">customer email (required).</param>
        /// <param name="name">customer name (required).</param>
        /// <param name="address">customer address (parameter is empty if this field was not send with create method).</param>
        /// <param name="city">customer city (parameter is empty if this field was not send with create method).</param>
        /// <param name="zip">customer postal code (parameter is empty if this field was not send with create method).</param>
        /// <param name="country">Two letters - see ISO 3166-1 document.</param>
        /// <param name="phone">customer phone number (parameter is empty if this field was not send with create method).</param>
        /// <param name="acceptTos">Acceptance of Tpay.com regulations done by customer on Merchant site.</param>
        /// <param name="apiPassword">API password. (required).</param>
        public CreateFields(int id = default(int), decimal amount = default(decimal), string description = default(string), string crc = default(string), string md5sum = default(string), int group = default(int), string resultUrl = default(string), string resultEmail = default(string), string merchantDescription = default(string), string customDescription = default(string), string returnUrl = default(string), string returnErrorUrl = default(string), LanguageEnum? language = LanguageEnum.Pl, string email = default(string), string name = default(string), string address = default(string), string city = default(string), string zip = default(string), string country = default(string), string phone = default(string), int acceptTos = default(int), string apiPassword = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for CreateFields and cannot be null");
            }
            else
            {
                this.Id = id;
            }

            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new InvalidDataException("amount is a required property for CreateFields and cannot be null");
            }
            else
            {
                this.Amount = amount;
            }

            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new InvalidDataException("description is a required property for CreateFields and cannot be null");
            }
            else
            {
                this.Description = description;
            }

            // to ensure "md5sum" is required (not null)
            if (md5sum == null)
            {
                throw new InvalidDataException("md5sum is a required property for CreateFields and cannot be null");
            }
            else
            {
                this.Md5sum = md5sum;
            }

            // to ensure "group" is required (not null)
            if (group == null)
            {
                throw new InvalidDataException("group is a required property for CreateFields and cannot be null");
            }
            else
            {
                this.Group = group;
            }

            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new InvalidDataException("email is a required property for CreateFields and cannot be null");
            }
            else
            {
                this.Email = email;
            }

            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for CreateFields and cannot be null");
            }
            else
            {
                this.Name = name;
            }

            // to ensure "apiPassword" is required (not null)
            if (apiPassword == null)
            {
                throw new InvalidDataException("apiPassword is a required property for CreateFields and cannot be null");
            }
            else
            {
                this.ApiPassword = apiPassword;
            }

            this.Crc = crc;
            this.ResultUrl = resultUrl;
            this.ResultEmail = resultEmail;
            this.MerchantDescription = merchantDescription;
            this.CustomDescription = customDescription;
            this.ReturnUrl = returnUrl;
            this.ReturnErrorUrl = returnErrorUrl;
            // use default value if no "language" provided
            if (language == null)
            {
                this.Language = LanguageEnum.Pl;
            }
            else
            {
                this.Language = language;
            }
            this.Address = address;
            this.City = city;
            this.Zip = zip;
            this.Country = country;
            this.Phone = phone;
            this.AcceptTos = acceptTos;
        }

        /// <summary>
        /// Merchant ID in Tpay.com system
        /// </summary>
        /// <value>Merchant ID in Tpay.com system</value>
        [DataMember(Name="id", EmitDefaultValue=true)]
        public int Id { get; set; }

        /// <summary>
        /// Transaction amount. Please always send the amount with two decimal places like 10.00
        /// </summary>
        /// <value>Transaction amount. Please always send the amount with two decimal places like 10.00</value>
        [DataMember(Name="amount", EmitDefaultValue=true)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Transaction description
        /// </summary>
        /// <value>Transaction description</value>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string Description { get; set; }

        /// <summary>
        /// Auxiliary parameter to identify the transaction on the merchant side. We do recommend to encode your crc value in base64. The exact value of crc used to create transaction will be returned in tpay payment notification as tr_crc parameter.
        /// </summary>
        /// <value>Auxiliary parameter to identify the transaction on the merchant side. We do recommend to encode your crc value in base64. The exact value of crc used to create transaction will be returned in tpay payment notification as tr_crc parameter.</value>
        [DataMember(Name="crc", EmitDefaultValue=false)]
        public string Crc { get; set; }

        /// <summary>
        /// md5 sum calculated from id.&#39;&amp;&#39;.amount.&#39;&amp;&#39;.crc.&#39;&amp;&#39;.security_code where dots means concatenation (security code can be found in merchant panel).
        /// </summary>
        /// <value>md5 sum calculated from id.&#39;&amp;&#39;.amount.&#39;&amp;&#39;.crc.&#39;&amp;&#39;.security_code where dots means concatenation (security code can be found in merchant panel).</value>
        [DataMember(Name="md5sum", EmitDefaultValue=true)]
        public string Md5sum { get; set; }

        /// <summary>
        /// Transaction group number see the \&quot;id\&quot; element in https://secure.tpay.com/groups-{id}0.js . For example https://secure.tpay.com/groups-10100.js or https://secure.tpay.com/groups-10100.js?json
        /// </summary>
        /// <value>Transaction group number see the \&quot;id\&quot; element in https://secure.tpay.com/groups-{id}0.js . For example https://secure.tpay.com/groups-10100.js or https://secure.tpay.com/groups-10100.js?json</value>
        [DataMember(Name="group", EmitDefaultValue=true)]
        public int Group { get; set; }

        /// <summary>
        /// Merchant endpoint for payment notification
        /// </summary>
        /// <value>Merchant endpoint for payment notification</value>
        [DataMember(Name="result_url", EmitDefaultValue=false)]
        public string ResultUrl { get; set; }

        /// <summary>
        /// Email address where notification after payment will be sent (overrides defined in merchant panel). You can add more addresses by comma concatenation.
        /// </summary>
        /// <value>Email address where notification after payment will be sent (overrides defined in merchant panel). You can add more addresses by comma concatenation.</value>
        [DataMember(Name="result_email", EmitDefaultValue=false)]
        public string ResultEmail { get; set; }

        /// <summary>
        /// Name of merchant displayed in transaction panel (overrides defined in merchant panel)
        /// </summary>
        /// <value>Name of merchant displayed in transaction panel (overrides defined in merchant panel)</value>
        [DataMember(Name="merchant_description", EmitDefaultValue=false)]
        public string MerchantDescription { get; set; }

        /// <summary>
        /// Additional info to be displayed in transaction panel (overrides defined in merchant panel)
        /// </summary>
        /// <value>Additional info to be displayed in transaction panel (overrides defined in merchant panel)</value>
        [DataMember(Name="custom_description", EmitDefaultValue=false)]
        public string CustomDescription { get; set; }

        /// <summary>
        /// url to redirect customer in case of payment success
        /// </summary>
        /// <value>url to redirect customer in case of payment success</value>
        [DataMember(Name="return_url", EmitDefaultValue=false)]
        public string ReturnUrl { get; set; }

        /// <summary>
        /// url to redirect customer in case of payment failure
        /// </summary>
        /// <value>url to redirect customer in case of payment failure</value>
        [DataMember(Name="return_error_url", EmitDefaultValue=false)]
        public string ReturnErrorUrl { get; set; }


        /// <summary>
        /// customer email
        /// </summary>
        /// <value>customer email</value>
        [DataMember(Name="email", EmitDefaultValue=true)]
        public string Email { get; set; }

        /// <summary>
        /// customer name
        /// </summary>
        /// <value>customer name</value>
        [DataMember(Name="name", EmitDefaultValue=true)]
        public string Name { get; set; }

        /// <summary>
        /// customer address (parameter is empty if this field was not send with create method)
        /// </summary>
        /// <value>customer address (parameter is empty if this field was not send with create method)</value>
        [DataMember(Name="address", EmitDefaultValue=false)]
        public string Address { get; set; }

        /// <summary>
        /// customer city (parameter is empty if this field was not send with create method)
        /// </summary>
        /// <value>customer city (parameter is empty if this field was not send with create method)</value>
        [DataMember(Name="city", EmitDefaultValue=false)]
        public string City { get; set; }

        /// <summary>
        /// customer postal code (parameter is empty if this field was not send with create method)
        /// </summary>
        /// <value>customer postal code (parameter is empty if this field was not send with create method)</value>
        [DataMember(Name="zip", EmitDefaultValue=false)]
        public string Zip { get; set; }

        /// <summary>
        /// Two letters - see ISO 3166-1 document
        /// </summary>
        /// <value>Two letters - see ISO 3166-1 document</value>
        [DataMember(Name="country", EmitDefaultValue=false)]
        public string Country { get; set; }

        /// <summary>
        /// customer phone number (parameter is empty if this field was not send with create method)
        /// </summary>
        /// <value>customer phone number (parameter is empty if this field was not send with create method)</value>
        [DataMember(Name="phone", EmitDefaultValue=false)]
        public string Phone { get; set; }

        /// <summary>
        /// Acceptance of Tpay.com regulations done by customer on Merchant site
        /// </summary>
        /// <value>Acceptance of Tpay.com regulations done by customer on Merchant site</value>
        [DataMember(Name="accept_tos", EmitDefaultValue=false)]
        public int AcceptTos { get; set; }

        /// <summary>
        /// API password.
        /// </summary>
        /// <value>API password.</value>
        [DataMember(Name="api_password", EmitDefaultValue=true)]
        public string ApiPassword { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateFields {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Crc: ").Append(Crc).Append("\n");
            sb.Append("  Md5sum: ").Append(Md5sum).Append("\n");
            sb.Append("  Group: ").Append(Group).Append("\n");
            sb.Append("  ResultUrl: ").Append(ResultUrl).Append("\n");
            sb.Append("  ResultEmail: ").Append(ResultEmail).Append("\n");
            sb.Append("  MerchantDescription: ").Append(MerchantDescription).Append("\n");
            sb.Append("  CustomDescription: ").Append(CustomDescription).Append("\n");
            sb.Append("  ReturnUrl: ").Append(ReturnUrl).Append("\n");
            sb.Append("  ReturnErrorUrl: ").Append(ReturnErrorUrl).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  Zip: ").Append(Zip).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  AcceptTos: ").Append(AcceptTos).Append("\n");
            sb.Append("  ApiPassword: ").Append(ApiPassword).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateFields);
        }

        /// <summary>
        /// Returns true if CreateFields instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateFields to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateFields input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Crc == input.Crc ||
                    (this.Crc != null &&
                    this.Crc.Equals(input.Crc))
                ) && 
                (
                    this.Md5sum == input.Md5sum ||
                    (this.Md5sum != null &&
                    this.Md5sum.Equals(input.Md5sum))
                ) && 
                (
                    this.Group == input.Group ||
                    (this.Group != null &&
                    this.Group.Equals(input.Group))
                ) && 
                (
                    this.ResultUrl == input.ResultUrl ||
                    (this.ResultUrl != null &&
                    this.ResultUrl.Equals(input.ResultUrl))
                ) && 
                (
                    this.ResultEmail == input.ResultEmail ||
                    (this.ResultEmail != null &&
                    this.ResultEmail.Equals(input.ResultEmail))
                ) && 
                (
                    this.MerchantDescription == input.MerchantDescription ||
                    (this.MerchantDescription != null &&
                    this.MerchantDescription.Equals(input.MerchantDescription))
                ) && 
                (
                    this.CustomDescription == input.CustomDescription ||
                    (this.CustomDescription != null &&
                    this.CustomDescription.Equals(input.CustomDescription))
                ) && 
                (
                    this.ReturnUrl == input.ReturnUrl ||
                    (this.ReturnUrl != null &&
                    this.ReturnUrl.Equals(input.ReturnUrl))
                ) && 
                (
                    this.ReturnErrorUrl == input.ReturnErrorUrl ||
                    (this.ReturnErrorUrl != null &&
                    this.ReturnErrorUrl.Equals(input.ReturnErrorUrl))
                ) && 
                (
                    this.Language == input.Language ||
                    (this.Language != null &&
                    this.Language.Equals(input.Language))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.City == input.City ||
                    (this.City != null &&
                    this.City.Equals(input.City))
                ) && 
                (
                    this.Zip == input.Zip ||
                    (this.Zip != null &&
                    this.Zip.Equals(input.Zip))
                ) && 
                (
                    this.Country == input.Country ||
                    (this.Country != null &&
                    this.Country.Equals(input.Country))
                ) && 
                (
                    this.Phone == input.Phone ||
                    (this.Phone != null &&
                    this.Phone.Equals(input.Phone))
                ) && 
                (
                    this.AcceptTos == input.AcceptTos ||
                    (this.AcceptTos != null &&
                    this.AcceptTos.Equals(input.AcceptTos))
                ) && 
                (
                    this.ApiPassword == input.ApiPassword ||
                    (this.ApiPassword != null &&
                    this.ApiPassword.Equals(input.ApiPassword))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.Crc != null)
                    hashCode = hashCode * 59 + this.Crc.GetHashCode();
                if (this.Md5sum != null)
                    hashCode = hashCode * 59 + this.Md5sum.GetHashCode();
                if (this.Group != null)
                    hashCode = hashCode * 59 + this.Group.GetHashCode();
                if (this.ResultUrl != null)
                    hashCode = hashCode * 59 + this.ResultUrl.GetHashCode();
                if (this.ResultEmail != null)
                    hashCode = hashCode * 59 + this.ResultEmail.GetHashCode();
                if (this.MerchantDescription != null)
                    hashCode = hashCode * 59 + this.MerchantDescription.GetHashCode();
                if (this.CustomDescription != null)
                    hashCode = hashCode * 59 + this.CustomDescription.GetHashCode();
                if (this.ReturnUrl != null)
                    hashCode = hashCode * 59 + this.ReturnUrl.GetHashCode();
                if (this.ReturnErrorUrl != null)
                    hashCode = hashCode * 59 + this.ReturnErrorUrl.GetHashCode();
                if (this.Language != null)
                    hashCode = hashCode * 59 + this.Language.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Address != null)
                    hashCode = hashCode * 59 + this.Address.GetHashCode();
                if (this.City != null)
                    hashCode = hashCode * 59 + this.City.GetHashCode();
                if (this.Zip != null)
                    hashCode = hashCode * 59 + this.Zip.GetHashCode();
                if (this.Country != null)
                    hashCode = hashCode * 59 + this.Country.GetHashCode();
                if (this.Phone != null)
                    hashCode = hashCode * 59 + this.Phone.GetHashCode();
                if (this.AcceptTos != null)
                    hashCode = hashCode * 59 + this.AcceptTos.GetHashCode();
                if (this.ApiPassword != null)
                    hashCode = hashCode * 59 + this.ApiPassword.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {

 
            // Amount (decimal) minimum
            if(this.Amount < (decimal)0.01)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Amount, must be a value greater than or equal to 0.01.", new [] { "Amount" });
            }

            // Description (string) maxLength
            if(this.Description != null && this.Description.Length > 128)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Description, length must be less than 128.", new [] { "Description" });
            }

 
            // Crc (string) maxLength
            if(this.Crc != null && this.Crc.Length > 255)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Crc, length must be less than 255.", new [] { "Crc" });
            }

 
            // Md5sum (string) maxLength
            if(this.Md5sum != null && this.Md5sum.Length > 32)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Md5sum, length must be less than 32.", new [] { "Md5sum" });
            }

            // Md5sum (string) minLength
            if(this.Md5sum != null && this.Md5sum.Length < 32)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Md5sum, length must be greater than 32.", new [] { "Md5sum" });
            }
 
            // ResultUrl (string) maxLength
            if(this.ResultUrl != null && this.ResultUrl.Length > 512)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ResultUrl, length must be less than 512.", new [] { "ResultUrl" });
            }

 
            // ResultEmail (string) maxLength
            if(this.ResultEmail != null && this.ResultEmail.Length > 256)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ResultEmail, length must be less than 256.", new [] { "ResultEmail" });
            }

 
            // MerchantDescription (string) maxLength
            if(this.MerchantDescription != null && this.MerchantDescription.Length > 128)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MerchantDescription, length must be less than 128.", new [] { "MerchantDescription" });
            }

 
            // CustomDescription (string) maxLength
            if(this.CustomDescription != null && this.CustomDescription.Length > 32)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CustomDescription, length must be less than 32.", new [] { "CustomDescription" });
            }

 
            // ReturnUrl (string) maxLength
            if(this.ReturnUrl != null && this.ReturnUrl.Length > 512)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ReturnUrl, length must be less than 512.", new [] { "ReturnUrl" });
            }

 
            // ReturnErrorUrl (string) maxLength
            if(this.ReturnErrorUrl != null && this.ReturnErrorUrl.Length > 512)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ReturnErrorUrl, length must be less than 512.", new [] { "ReturnErrorUrl" });
            }

 
            // Email (string) maxLength
            if(this.Email != null && this.Email.Length > 64)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Email, length must be less than 64.", new [] { "Email" });
            }

 
            // Name (string) maxLength
            if(this.Name != null && this.Name.Length > 64)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be less than 64.", new [] { "Name" });
            }

 
            // ApiPassword (string) maxLength
            if(this.ApiPassword != null && this.ApiPassword.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ApiPassword, length must be less than 40.", new [] { "ApiPassword" });
            }

 
            yield break;
        }
    }

}
