/*
 * Tpay.com Technical Documentation
 *
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"bda5eda723bf1ae71a82e90a249803d3f852248d\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: pt@tpay.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// language for 3DS gateway
    /// </summary>
    /// <value>language for 3DS gateway</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Language
    {
        /// <summary>
        /// Enum Pl for value: pl
        /// </summary>
        [EnumMember(Value = "pl")]
        Pl = 1,

        /// <summary>
        /// Enum En for value: en
        /// </summary>
        [EnumMember(Value = "en")]
        En = 2,

        /// <summary>
        /// Enum Fr for value: fr
        /// </summary>
        [EnumMember(Value = "fr")]
        Fr = 3,

        /// <summary>
        /// Enum Es for value: es
        /// </summary>
        [EnumMember(Value = "es")]
        Es = 4,

        /// <summary>
        /// Enum It for value: it
        /// </summary>
        [EnumMember(Value = "it")]
        It = 5,

        /// <summary>
        /// Enum Ru for value: ru
        /// </summary>
        [EnumMember(Value = "ru")]
        Ru = 6,

        /// <summary>
        /// Enum De for value: de
        /// </summary>
        [EnumMember(Value = "de")]
        De = 7,

        /// <summary>
        /// Enum Uk for value: uk
        /// </summary>
        [EnumMember(Value = "uk")]
        Uk = 8,

        /// <summary>
        /// Enum Ro for value: ro
        /// </summary>
        [EnumMember(Value = "ro")]
        Ro = 9,

        /// <summary>
        /// Enum Hu for value: hu
        /// </summary>
        [EnumMember(Value = "hu")]
        Hu = 10,

        /// <summary>
        /// Enum Cs for value: cs
        /// </summary>
        [EnumMember(Value = "cs")]
        Cs = 11,

        /// <summary>
        /// Enum Bg for value: bg
        /// </summary>
        [EnumMember(Value = "bg")]
        Bg = 12,

        /// <summary>
        /// Enum Hr for value: hr
        /// </summary>
        [EnumMember(Value = "hr")]
        Hr = 13

    }

}
