/*
 * Tpay.com Technical Documentation
 *
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"bda5eda723bf1ae71a82e90a249803d3f852248d\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: pt@tpay.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// MasspaymentAuthorizeFields
    /// </summary>
    [DataContract]
    public partial class MasspaymentAuthorizeFields :  IEquatable<MasspaymentAuthorizeFields>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MasspaymentAuthorizeFields" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MasspaymentAuthorizeFields() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MasspaymentAuthorizeFields" /> class.
        /// </summary>
        /// <param name="packId">ID of created pack using method create. (required).</param>
        /// <param name="apiPassword">API password. (required).</param>
        public MasspaymentAuthorizeFields(int packId = default(int), string apiPassword = default(string))
        {
            // to ensure "packId" is required (not null)
            if (packId == null)
            {
                throw new InvalidDataException("packId is a required property for MasspaymentAuthorizeFields and cannot be null");
            }
            else
            {
                this.PackId = packId;
            }

            // to ensure "apiPassword" is required (not null)
            if (apiPassword == null)
            {
                throw new InvalidDataException("apiPassword is a required property for MasspaymentAuthorizeFields and cannot be null");
            }
            else
            {
                this.ApiPassword = apiPassword;
            }

        }

        /// <summary>
        /// ID of created pack using method create.
        /// </summary>
        /// <value>ID of created pack using method create.</value>
        [DataMember(Name="pack_id", EmitDefaultValue=true)]
        public int PackId { get; set; }

        /// <summary>
        /// API password.
        /// </summary>
        /// <value>API password.</value>
        [DataMember(Name="api_password", EmitDefaultValue=true)]
        public string ApiPassword { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MasspaymentAuthorizeFields {\n");
            sb.Append("  PackId: ").Append(PackId).Append("\n");
            sb.Append("  ApiPassword: ").Append(ApiPassword).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MasspaymentAuthorizeFields);
        }

        /// <summary>
        /// Returns true if MasspaymentAuthorizeFields instances are equal
        /// </summary>
        /// <param name="input">Instance of MasspaymentAuthorizeFields to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MasspaymentAuthorizeFields input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PackId == input.PackId ||
                    (this.PackId != null &&
                    this.PackId.Equals(input.PackId))
                ) && 
                (
                    this.ApiPassword == input.ApiPassword ||
                    (this.ApiPassword != null &&
                    this.ApiPassword.Equals(input.ApiPassword))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PackId != null)
                    hashCode = hashCode * 59 + this.PackId.GetHashCode();
                if (this.ApiPassword != null)
                    hashCode = hashCode * 59 + this.ApiPassword.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ApiPassword (string) maxLength
            if(this.ApiPassword != null && this.ApiPassword.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ApiPassword, length must be less than 40.", new [] { "ApiPassword" });
            }

 
            yield break;
        }
    }

}
