/*
 * Tpay.com Technical Documentation
 *
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"bda5eda723bf1ae71a82e90a249803d3f852248d\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: pt@tpay.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PaymentAttempts
    /// </summary>
    [DataContract]
    public partial class PaymentAttempts :  IEquatable<PaymentAttempts>, IValidatableObject
    {
        /// <summary>
        /// Error code if any occurred. Null if payment was successful. See Transaction API error codes for more details.
        /// </summary>
        /// <value>Error code if any occurred. Null if payment was successful. See Transaction API error codes for more details.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PaymentErrorCodeEnum
        {
            /// <summary>
            /// Enum ERR100 for value: ERR100
            /// </summary>
            [EnumMember(Value = "ERR100")]
            ERR100 = 1,

            /// <summary>
            /// Enum ERR101 for value: ERR101
            /// </summary>
            [EnumMember(Value = "ERR101")]
            ERR101 = 2,

            /// <summary>
            /// Enum ERR102 for value: ERR102
            /// </summary>
            [EnumMember(Value = "ERR102")]
            ERR102 = 3,

            /// <summary>
            /// Enum ERR103 for value: ERR103
            /// </summary>
            [EnumMember(Value = "ERR103")]
            ERR103 = 4,

            /// <summary>
            /// Enum ERR104 for value: ERR104
            /// </summary>
            [EnumMember(Value = "ERR104")]
            ERR104 = 5

        }

        /// <summary>
        /// Error code if any occurred. Null if payment was successful. See Transaction API error codes for more details.
        /// </summary>
        /// <value>Error code if any occurred. Null if payment was successful. See Transaction API error codes for more details.</value>
        [DataMember(Name="paymentErrorCode", EmitDefaultValue=false)]
        public PaymentErrorCodeEnum? PaymentErrorCode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentAttempts" /> class.
        /// </summary>
        /// <param name="date">Time of payment attempt.</param>
        /// <param name="paymentErrorCode">Error code if any occurred. Null if payment was successful. See Transaction API error codes for more details..</param>
        public PaymentAttempts(string date = default(string), PaymentErrorCodeEnum? paymentErrorCode = default(PaymentErrorCodeEnum?))
        {
            this.Date = date;
            this.PaymentErrorCode = paymentErrorCode;
        }

        /// <summary>
        /// Time of payment attempt
        /// </summary>
        /// <value>Time of payment attempt</value>
        [DataMember(Name="date", EmitDefaultValue=false)]
        public string Date { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentAttempts {\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  PaymentErrorCode: ").Append(PaymentErrorCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentAttempts);
        }

        /// <summary>
        /// Returns true if PaymentAttempts instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentAttempts to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentAttempts input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Date == input.Date ||
                    (this.Date != null &&
                    this.Date.Equals(input.Date))
                ) && 
                (
                    this.PaymentErrorCode == input.PaymentErrorCode ||
                    (this.PaymentErrorCode != null &&
                    this.PaymentErrorCode.Equals(input.PaymentErrorCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Date != null)
                    hashCode = hashCode * 59 + this.Date.GetHashCode();
                if (this.PaymentErrorCode != null)
                    hashCode = hashCode * 59 + this.PaymentErrorCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
