/*
 * Tpay.com Technical Documentation
 *
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"bda5eda723bf1ae71a82e90a249803d3f852248d\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: pt@tpay.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RefundFields
    /// </summary>
    [DataContract]
    public partial class RefundFields :  IEquatable<RefundFields>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RefundFields" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RefundFields() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RefundFields" /> class.
        /// </summary>
        /// <param name="cliAuth">Client token.</param>
        /// <param name="saleAuth">Transaction id in tpay.com system.</param>
        /// <param name="desc">desc (required).</param>
        /// <param name="currency">transaction currency in ISO numeric format (default to 985).</param>
        /// <param name="amount">transaction amount casted to float.</param>
        /// <param name="language">language.</param>
        /// <param name="apiPassword">API password. (required).</param>
        /// <param name="sign">Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): hash_alg (method + cli_auth + sale_auth + desc + amount + currency + language + verification code); where + means concatenation with ampersand symbol. ie. currency + language &#x3D; 985&amp;pl (required).</param>
        public RefundFields(string cliAuth = default(string), string saleAuth = default(string), string desc = default(string), int currency = 985, decimal amount = default(decimal), Language language = default(Language), string apiPassword = default(string), string sign = default(string))
        {
            // to ensure "desc" is required (not null)
            if (desc == null)
            {
                throw new InvalidDataException("desc is a required property for RefundFields and cannot be null");
            }
            else
            {
                this.Desc = desc;
            }

            // to ensure "apiPassword" is required (not null)
            if (apiPassword == null)
            {
                throw new InvalidDataException("apiPassword is a required property for RefundFields and cannot be null");
            }
            else
            {
                this.ApiPassword = apiPassword;
            }

            // to ensure "sign" is required (not null)
            if (sign == null)
            {
                throw new InvalidDataException("sign is a required property for RefundFields and cannot be null");
            }
            else
            {
                this.Sign = sign;
            }

            this.CliAuth = cliAuth;
            this.SaleAuth = saleAuth;
            // use default value if no "currency" provided
            if (currency == null)
            {
                this.Currency = 985;
            }
            else
            {
                this.Currency = currency;
            }
            this.Amount = amount;
            this.Language = language;
        }

        /// <summary>
        /// Client token
        /// </summary>
        /// <value>Client token</value>
        [DataMember(Name="cli_auth", EmitDefaultValue=false)]
        public string CliAuth { get; set; }

        /// <summary>
        /// Transaction id in tpay.com system
        /// </summary>
        /// <value>Transaction id in tpay.com system</value>
        [DataMember(Name="sale_auth", EmitDefaultValue=false)]
        public string SaleAuth { get; set; }

        /// <summary>
        /// Gets or Sets Desc
        /// </summary>
        [DataMember(Name="desc", EmitDefaultValue=true)]
        public string Desc { get; set; }

        /// <summary>
        /// transaction currency in ISO numeric format
        /// </summary>
        /// <value>transaction currency in ISO numeric format</value>
        [DataMember(Name="currency", EmitDefaultValue=false)]
        public int Currency { get; set; }

        /// <summary>
        /// transaction amount casted to float
        /// </summary>
        /// <value>transaction amount casted to float</value>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [DataMember(Name="language", EmitDefaultValue=false)]
        public Language Language { get; set; }

        /// <summary>
        /// API password.
        /// </summary>
        /// <value>API password.</value>
        [DataMember(Name="api_password", EmitDefaultValue=true)]
        public string ApiPassword { get; set; }

        /// <summary>
        /// Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): hash_alg (method + cli_auth + sale_auth + desc + amount + currency + language + verification code); where + means concatenation with ampersand symbol. ie. currency + language &#x3D; 985&amp;pl
        /// </summary>
        /// <value>Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): hash_alg (method + cli_auth + sale_auth + desc + amount + currency + language + verification code); where + means concatenation with ampersand symbol. ie. currency + language &#x3D; 985&amp;pl</value>
        [DataMember(Name="sign", EmitDefaultValue=true)]
        public string Sign { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RefundFields {\n");
            sb.Append("  CliAuth: ").Append(CliAuth).Append("\n");
            sb.Append("  SaleAuth: ").Append(SaleAuth).Append("\n");
            sb.Append("  Desc: ").Append(Desc).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  ApiPassword: ").Append(ApiPassword).Append("\n");
            sb.Append("  Sign: ").Append(Sign).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RefundFields);
        }

        /// <summary>
        /// Returns true if RefundFields instances are equal
        /// </summary>
        /// <param name="input">Instance of RefundFields to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RefundFields input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CliAuth == input.CliAuth ||
                    (this.CliAuth != null &&
                    this.CliAuth.Equals(input.CliAuth))
                ) && 
                (
                    this.SaleAuth == input.SaleAuth ||
                    (this.SaleAuth != null &&
                    this.SaleAuth.Equals(input.SaleAuth))
                ) && 
                (
                    this.Desc == input.Desc ||
                    (this.Desc != null &&
                    this.Desc.Equals(input.Desc))
                ) && 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.Language == input.Language ||
                    (this.Language != null &&
                    this.Language.Equals(input.Language))
                ) && 
                (
                    this.ApiPassword == input.ApiPassword ||
                    (this.ApiPassword != null &&
                    this.ApiPassword.Equals(input.ApiPassword))
                ) && 
                (
                    this.Sign == input.Sign ||
                    (this.Sign != null &&
                    this.Sign.Equals(input.Sign))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CliAuth != null)
                    hashCode = hashCode * 59 + this.CliAuth.GetHashCode();
                if (this.SaleAuth != null)
                    hashCode = hashCode * 59 + this.SaleAuth.GetHashCode();
                if (this.Desc != null)
                    hashCode = hashCode * 59 + this.Desc.GetHashCode();
                if (this.Currency != null)
                    hashCode = hashCode * 59 + this.Currency.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.Language != null)
                    hashCode = hashCode * 59 + this.Language.GetHashCode();
                if (this.ApiPassword != null)
                    hashCode = hashCode * 59 + this.ApiPassword.GetHashCode();
                if (this.Sign != null)
                    hashCode = hashCode * 59 + this.Sign.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CliAuth (string) maxLength
            if(this.CliAuth != null && this.CliAuth.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CliAuth, length must be less than 40.", new [] { "CliAuth" });
            }

            // CliAuth (string) minLength
            if(this.CliAuth != null && this.CliAuth.Length < 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CliAuth, length must be greater than 40.", new [] { "CliAuth" });
            }
 
            // SaleAuth (string) maxLength
            if(this.SaleAuth != null && this.SaleAuth.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SaleAuth, length must be less than 40.", new [] { "SaleAuth" });
            }

            // SaleAuth (string) minLength
            if(this.SaleAuth != null && this.SaleAuth.Length < 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SaleAuth, length must be greater than 40.", new [] { "SaleAuth" });
            }
 
            // Desc (string) maxLength
            if(this.Desc != null && this.Desc.Length > 128)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Desc, length must be less than 128.", new [] { "Desc" });
            }

            // Desc (string) minLength
            if(this.Desc != null && this.Desc.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Desc, length must be greater than 1.", new [] { "Desc" });
            }
 

 

 
            // Amount (decimal) minimum
            if(this.Amount < (decimal)0.1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Amount, must be a value greater than or equal to 0.1.", new [] { "Amount" });
            }

            // ApiPassword (string) maxLength
            if(this.ApiPassword != null && this.ApiPassword.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ApiPassword, length must be less than 40.", new [] { "ApiPassword" });
            }

 
            yield break;
        }
    }

}
