/*
 * Tpay.com Technical Documentation
 *
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"bda5eda723bf1ae71a82e90a249803d3f852248d\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: pt@tpay.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RegisterSaleFields
    /// </summary>
    [DataContract]
    public partial class RegisterSaleFields :  IEquatable<RegisterSaleFields>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterSaleFields" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RegisterSaleFields() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterSaleFields" /> class.
        /// </summary>
        /// <param name="name">customer name (required).</param>
        /// <param name="email">customer email (required).</param>
        /// <param name="desc">transaction description (required).</param>
        /// <param name="amount">transaction amount casted to float (required).</param>
        /// <param name="apiPassword">API password. (required).</param>
        /// <param name="sign">Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): sha1(method + name + email + desc + amount + currency + order_id + onetimer + language + verification code) where + means concatenation with ampersand symbol. ie. name + email &#x3D; john done&amp;john.doe@example.com (required).</param>
        /// <param name="currency">transaction currency in ISO numeric format (default to 985).</param>
        /// <param name="onetimer">onetimer.</param>
        /// <param name="powUrl">url to redirect customer in case of payment success.</param>
        /// <param name="powUrlBlad">url to redirect customer in case of payment failure.</param>
        /// <param name="orderId">merchant order ID used to recognise payment.</param>
        /// <param name="language">language.</param>
        public RegisterSaleFields(string name = default(string), string email = default(string), string desc = default(string), decimal amount = default(decimal), string apiPassword = default(string), string sign = default(string), int currency = 985, Onetimer onetimer = default(Onetimer), string powUrl = default(string), string powUrlBlad = default(string), string orderId = default(string), Language language = default(Language))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for RegisterSaleFields and cannot be null");
            }
            else
            {
                this.Name = name;
            }

            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new InvalidDataException("email is a required property for RegisterSaleFields and cannot be null");
            }
            else
            {
                this.Email = email;
            }

            // to ensure "desc" is required (not null)
            if (desc == null)
            {
                throw new InvalidDataException("desc is a required property for RegisterSaleFields and cannot be null");
            }
            else
            {
                this.Desc = desc;
            }

            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new InvalidDataException("amount is a required property for RegisterSaleFields and cannot be null");
            }
            else
            {
                this.Amount = amount;
            }

            // to ensure "apiPassword" is required (not null)
            if (apiPassword == null)
            {
                throw new InvalidDataException("apiPassword is a required property for RegisterSaleFields and cannot be null");
            }
            else
            {
                this.ApiPassword = apiPassword;
            }

            // to ensure "sign" is required (not null)
            if (sign == null)
            {
                throw new InvalidDataException("sign is a required property for RegisterSaleFields and cannot be null");
            }
            else
            {
                this.Sign = sign;
            }

            // use default value if no "currency" provided
            if (currency == null)
            {
                this.Currency = 985;
            }
            else
            {
                this.Currency = currency;
            }
            this.Onetimer = onetimer;
            this.PowUrl = powUrl;
            this.PowUrlBlad = powUrlBlad;
            this.OrderId = orderId;
            this.Language = language;
        }

        /// <summary>
        /// customer name
        /// </summary>
        /// <value>customer name</value>
        [DataMember(Name="name", EmitDefaultValue=true)]
        public string Name { get; set; }

        /// <summary>
        /// customer email
        /// </summary>
        /// <value>customer email</value>
        [DataMember(Name="email", EmitDefaultValue=true)]
        public string Email { get; set; }

        /// <summary>
        /// transaction description
        /// </summary>
        /// <value>transaction description</value>
        [DataMember(Name="desc", EmitDefaultValue=true)]
        public string Desc { get; set; }

        /// <summary>
        /// transaction amount casted to float
        /// </summary>
        /// <value>transaction amount casted to float</value>
        [DataMember(Name="amount", EmitDefaultValue=true)]
        public decimal Amount { get; set; }

        /// <summary>
        /// API password.
        /// </summary>
        /// <value>API password.</value>
        [DataMember(Name="api_password", EmitDefaultValue=true)]
        public string ApiPassword { get; set; }

        /// <summary>
        /// Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): sha1(method + name + email + desc + amount + currency + order_id + onetimer + language + verification code) where + means concatenation with ampersand symbol. ie. name + email &#x3D; john done&amp;john.doe@example.com
        /// </summary>
        /// <value>Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): sha1(method + name + email + desc + amount + currency + order_id + onetimer + language + verification code) where + means concatenation with ampersand symbol. ie. name + email &#x3D; john done&amp;john.doe@example.com</value>
        [DataMember(Name="sign", EmitDefaultValue=true)]
        public string Sign { get; set; }

        /// <summary>
        /// transaction currency in ISO numeric format
        /// </summary>
        /// <value>transaction currency in ISO numeric format</value>
        [DataMember(Name="currency", EmitDefaultValue=false)]
        public int Currency { get; set; }

        /// <summary>
        /// Gets or Sets Onetimer
        /// </summary>
        [DataMember(Name="onetimer", EmitDefaultValue=false)]
        public Onetimer Onetimer { get; set; }

        /// <summary>
        /// url to redirect customer in case of payment success
        /// </summary>
        /// <value>url to redirect customer in case of payment success</value>
        [DataMember(Name="pow_url", EmitDefaultValue=false)]
        public string PowUrl { get; set; }

        /// <summary>
        /// url to redirect customer in case of payment failure
        /// </summary>
        /// <value>url to redirect customer in case of payment failure</value>
        [DataMember(Name="pow_url_blad", EmitDefaultValue=false)]
        public string PowUrlBlad { get; set; }

        /// <summary>
        /// merchant order ID used to recognise payment
        /// </summary>
        /// <value>merchant order ID used to recognise payment</value>
        [DataMember(Name="order_id", EmitDefaultValue=false)]
        public string OrderId { get; set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [DataMember(Name="language", EmitDefaultValue=false)]
        public Language Language { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RegisterSaleFields {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Desc: ").Append(Desc).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  ApiPassword: ").Append(ApiPassword).Append("\n");
            sb.Append("  Sign: ").Append(Sign).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Onetimer: ").Append(Onetimer).Append("\n");
            sb.Append("  PowUrl: ").Append(PowUrl).Append("\n");
            sb.Append("  PowUrlBlad: ").Append(PowUrlBlad).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RegisterSaleFields);
        }

        /// <summary>
        /// Returns true if RegisterSaleFields instances are equal
        /// </summary>
        /// <param name="input">Instance of RegisterSaleFields to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RegisterSaleFields input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.Desc == input.Desc ||
                    (this.Desc != null &&
                    this.Desc.Equals(input.Desc))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.ApiPassword == input.ApiPassword ||
                    (this.ApiPassword != null &&
                    this.ApiPassword.Equals(input.ApiPassword))
                ) && 
                (
                    this.Sign == input.Sign ||
                    (this.Sign != null &&
                    this.Sign.Equals(input.Sign))
                ) && 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                ) && 
                (
                    this.Onetimer == input.Onetimer ||
                    (this.Onetimer != null &&
                    this.Onetimer.Equals(input.Onetimer))
                ) && 
                (
                    this.PowUrl == input.PowUrl ||
                    (this.PowUrl != null &&
                    this.PowUrl.Equals(input.PowUrl))
                ) && 
                (
                    this.PowUrlBlad == input.PowUrlBlad ||
                    (this.PowUrlBlad != null &&
                    this.PowUrlBlad.Equals(input.PowUrlBlad))
                ) && 
                (
                    this.OrderId == input.OrderId ||
                    (this.OrderId != null &&
                    this.OrderId.Equals(input.OrderId))
                ) && 
                (
                    this.Language == input.Language ||
                    (this.Language != null &&
                    this.Language.Equals(input.Language))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.Desc != null)
                    hashCode = hashCode * 59 + this.Desc.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.ApiPassword != null)
                    hashCode = hashCode * 59 + this.ApiPassword.GetHashCode();
                if (this.Sign != null)
                    hashCode = hashCode * 59 + this.Sign.GetHashCode();
                if (this.Currency != null)
                    hashCode = hashCode * 59 + this.Currency.GetHashCode();
                if (this.Onetimer != null)
                    hashCode = hashCode * 59 + this.Onetimer.GetHashCode();
                if (this.PowUrl != null)
                    hashCode = hashCode * 59 + this.PowUrl.GetHashCode();
                if (this.PowUrlBlad != null)
                    hashCode = hashCode * 59 + this.PowUrlBlad.GetHashCode();
                if (this.OrderId != null)
                    hashCode = hashCode * 59 + this.OrderId.GetHashCode();
                if (this.Language != null)
                    hashCode = hashCode * 59 + this.Language.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if(this.Name != null && this.Name.Length > 64)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be less than 64.", new [] { "Name" });
            }

 
            // Email (string) maxLength
            if(this.Email != null && this.Email.Length > 64)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Email, length must be less than 64.", new [] { "Email" });
            }

 
            // Desc (string) maxLength
            if(this.Desc != null && this.Desc.Length > 128)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Desc, length must be less than 128.", new [] { "Desc" });
            }

 

 
            // Amount (decimal) minimum
            if(this.Amount < (decimal)0.1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Amount, must be a value greater than or equal to 0.1.", new [] { "Amount" });
            }

            // ApiPassword (string) maxLength
            if(this.ApiPassword != null && this.ApiPassword.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ApiPassword, length must be less than 40.", new [] { "ApiPassword" });
            }

 
            // Sign (string) maxLength
            if(this.Sign != null && this.Sign.Length > 128)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Sign, length must be less than 128.", new [] { "Sign" });
            }

            // Sign (string) minLength
            if(this.Sign != null && this.Sign.Length < 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Sign, length must be greater than 40.", new [] { "Sign" });
            }
 

 
            // PowUrl (string) maxLength
            if(this.PowUrl != null && this.PowUrl.Length > 512)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PowUrl, length must be less than 512.", new [] { "PowUrl" });
            }

 
            // PowUrlBlad (string) maxLength
            if(this.PowUrlBlad != null && this.PowUrlBlad.Length > 512)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PowUrlBlad, length must be less than 512.", new [] { "PowUrlBlad" });
            }

 
            // OrderId (string) maxLength
            if(this.OrderId != null && this.OrderId.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for OrderId, length must be less than 40.", new [] { "OrderId" });
            }

 
            yield break;
        }
    }

}
