/*
 * Tpay.com Technical Documentation
 *
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"bda5eda723bf1ae71a82e90a249803d3f852248d\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: pt@tpay.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Successful response schema
    /// </summary>
    [DataContract]
    public partial class RegisterSaleResponse :  IEquatable<RegisterSaleResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterSaleResponse" /> class.
        /// </summary>
        /// <param name="result">result.</param>
        /// <param name="saleAuth">Transaction id in tpay.com system.</param>
        /// <param name="sign">Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): sha1(sale_auth + verification code) where + means concatenation..</param>
        /// <param name="errCode">errCode.</param>
        /// <param name="errDesc">Error code description if an error occurs or not present in response. - see \&quot;Card Payments Rejection Codes\&quot; for more details.</param>
        public RegisterSaleResponse(Result result = default(Result), string saleAuth = default(string), string sign = default(string), CardsErrCode errCode = default(CardsErrCode), string errDesc = default(string))
        {
            this.Result = result;
            this.SaleAuth = saleAuth;
            this.Sign = sign;
            this.ErrCode = errCode;
            this.ErrDesc = errDesc;
        }

        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [DataMember(Name="result", EmitDefaultValue=false)]
        public Result Result { get; set; }

        /// <summary>
        /// Transaction id in tpay.com system
        /// </summary>
        /// <value>Transaction id in tpay.com system</value>
        [DataMember(Name="sale_auth", EmitDefaultValue=false)]
        public string SaleAuth { get; set; }

        /// <summary>
        /// Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): sha1(sale_auth + verification code) where + means concatenation.
        /// </summary>
        /// <value>Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): sha1(sale_auth + verification code) where + means concatenation.</value>
        [DataMember(Name="sign", EmitDefaultValue=false)]
        public string Sign { get; set; }

        /// <summary>
        /// Gets or Sets ErrCode
        /// </summary>
        [DataMember(Name="err_code", EmitDefaultValue=false)]
        public CardsErrCode ErrCode { get; set; }

        /// <summary>
        /// Error code description if an error occurs or not present in response. - see \&quot;Card Payments Rejection Codes\&quot; for more details
        /// </summary>
        /// <value>Error code description if an error occurs or not present in response. - see \&quot;Card Payments Rejection Codes\&quot; for more details</value>
        [DataMember(Name="err_desc", EmitDefaultValue=false)]
        public string ErrDesc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RegisterSaleResponse {\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  SaleAuth: ").Append(SaleAuth).Append("\n");
            sb.Append("  Sign: ").Append(Sign).Append("\n");
            sb.Append("  ErrCode: ").Append(ErrCode).Append("\n");
            sb.Append("  ErrDesc: ").Append(ErrDesc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RegisterSaleResponse);
        }

        /// <summary>
        /// Returns true if RegisterSaleResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of RegisterSaleResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RegisterSaleResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Result == input.Result ||
                    (this.Result != null &&
                    this.Result.Equals(input.Result))
                ) && 
                (
                    this.SaleAuth == input.SaleAuth ||
                    (this.SaleAuth != null &&
                    this.SaleAuth.Equals(input.SaleAuth))
                ) && 
                (
                    this.Sign == input.Sign ||
                    (this.Sign != null &&
                    this.Sign.Equals(input.Sign))
                ) && 
                (
                    this.ErrCode == input.ErrCode ||
                    (this.ErrCode != null &&
                    this.ErrCode.Equals(input.ErrCode))
                ) && 
                (
                    this.ErrDesc == input.ErrDesc ||
                    (this.ErrDesc != null &&
                    this.ErrDesc.Equals(input.ErrDesc))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Result != null)
                    hashCode = hashCode * 59 + this.Result.GetHashCode();
                if (this.SaleAuth != null)
                    hashCode = hashCode * 59 + this.SaleAuth.GetHashCode();
                if (this.Sign != null)
                    hashCode = hashCode * 59 + this.Sign.GetHashCode();
                if (this.ErrCode != null)
                    hashCode = hashCode * 59 + this.ErrCode.GetHashCode();
                if (this.ErrDesc != null)
                    hashCode = hashCode * 59 + this.ErrDesc.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SaleAuth (string) maxLength
            if(this.SaleAuth != null && this.SaleAuth.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SaleAuth, length must be less than 40.", new [] { "SaleAuth" });
            }

            // SaleAuth (string) minLength
            if(this.SaleAuth != null && this.SaleAuth.Length < 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SaleAuth, length must be greater than 40.", new [] { "SaleAuth" });
            }
 
            yield break;
        }
    }

}
