/*
 * Tpay.com Technical Documentation
 *
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"bda5eda723bf1ae71a82e90a249803d3f852248d\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: pt@tpay.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SaleFields
    /// </summary>
    [DataContract]
    public partial class SaleFields :  IEquatable<SaleFields>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SaleFields" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SaleFields() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SaleFields" /> class.
        /// </summary>
        /// <param name="cliAuth">Client token (required).</param>
        /// <param name="saleAuth">Transaction id in tpay.com system (required).</param>
        /// <param name="apiPassword">API password. (required).</param>
        /// <param name="sign">Request sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): hash_alg (method + cli_auth + sale_auth + verification code); where + means concatenation with ampersand symbol. ie. name + email &#x3D; john done&amp;john.doe@example.com. Passed cli_auth has to match with cli_auth used while creating sale in presale method.  (required).</param>
        public SaleFields(string cliAuth = default(string), string saleAuth = default(string), string apiPassword = default(string), string sign = default(string))
        {
            // to ensure "cliAuth" is required (not null)
            if (cliAuth == null)
            {
                throw new InvalidDataException("cliAuth is a required property for SaleFields and cannot be null");
            }
            else
            {
                this.CliAuth = cliAuth;
            }

            // to ensure "saleAuth" is required (not null)
            if (saleAuth == null)
            {
                throw new InvalidDataException("saleAuth is a required property for SaleFields and cannot be null");
            }
            else
            {
                this.SaleAuth = saleAuth;
            }

            // to ensure "apiPassword" is required (not null)
            if (apiPassword == null)
            {
                throw new InvalidDataException("apiPassword is a required property for SaleFields and cannot be null");
            }
            else
            {
                this.ApiPassword = apiPassword;
            }

            // to ensure "sign" is required (not null)
            if (sign == null)
            {
                throw new InvalidDataException("sign is a required property for SaleFields and cannot be null");
            }
            else
            {
                this.Sign = sign;
            }

        }

        /// <summary>
        /// Client token
        /// </summary>
        /// <value>Client token</value>
        [DataMember(Name="cli_auth", EmitDefaultValue=true)]
        public string CliAuth { get; set; }

        /// <summary>
        /// Transaction id in tpay.com system
        /// </summary>
        /// <value>Transaction id in tpay.com system</value>
        [DataMember(Name="sale_auth", EmitDefaultValue=true)]
        public string SaleAuth { get; set; }

        /// <summary>
        /// API password.
        /// </summary>
        /// <value>API password.</value>
        [DataMember(Name="api_password", EmitDefaultValue=true)]
        public string ApiPassword { get; set; }

        /// <summary>
        /// Request sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): hash_alg (method + cli_auth + sale_auth + verification code); where + means concatenation with ampersand symbol. ie. name + email &#x3D; john done&amp;john.doe@example.com. Passed cli_auth has to match with cli_auth used while creating sale in presale method. 
        /// </summary>
        /// <value>Request sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): hash_alg (method + cli_auth + sale_auth + verification code); where + means concatenation with ampersand symbol. ie. name + email &#x3D; john done&amp;john.doe@example.com. Passed cli_auth has to match with cli_auth used while creating sale in presale method. </value>
        [DataMember(Name="sign", EmitDefaultValue=true)]
        public string Sign { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SaleFields {\n");
            sb.Append("  CliAuth: ").Append(CliAuth).Append("\n");
            sb.Append("  SaleAuth: ").Append(SaleAuth).Append("\n");
            sb.Append("  ApiPassword: ").Append(ApiPassword).Append("\n");
            sb.Append("  Sign: ").Append(Sign).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SaleFields);
        }

        /// <summary>
        /// Returns true if SaleFields instances are equal
        /// </summary>
        /// <param name="input">Instance of SaleFields to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SaleFields input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CliAuth == input.CliAuth ||
                    (this.CliAuth != null &&
                    this.CliAuth.Equals(input.CliAuth))
                ) && 
                (
                    this.SaleAuth == input.SaleAuth ||
                    (this.SaleAuth != null &&
                    this.SaleAuth.Equals(input.SaleAuth))
                ) && 
                (
                    this.ApiPassword == input.ApiPassword ||
                    (this.ApiPassword != null &&
                    this.ApiPassword.Equals(input.ApiPassword))
                ) && 
                (
                    this.Sign == input.Sign ||
                    (this.Sign != null &&
                    this.Sign.Equals(input.Sign))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CliAuth != null)
                    hashCode = hashCode * 59 + this.CliAuth.GetHashCode();
                if (this.SaleAuth != null)
                    hashCode = hashCode * 59 + this.SaleAuth.GetHashCode();
                if (this.ApiPassword != null)
                    hashCode = hashCode * 59 + this.ApiPassword.GetHashCode();
                if (this.Sign != null)
                    hashCode = hashCode * 59 + this.Sign.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CliAuth (string) maxLength
            if(this.CliAuth != null && this.CliAuth.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CliAuth, length must be less than 40.", new [] { "CliAuth" });
            }

            // CliAuth (string) minLength
            if(this.CliAuth != null && this.CliAuth.Length < 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CliAuth, length must be greater than 40.", new [] { "CliAuth" });
            }
 
            // SaleAuth (string) maxLength
            if(this.SaleAuth != null && this.SaleAuth.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SaleAuth, length must be less than 40.", new [] { "SaleAuth" });
            }

            // SaleAuth (string) minLength
            if(this.SaleAuth != null && this.SaleAuth.Length < 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SaleAuth, length must be greater than 40.", new [] { "SaleAuth" });
            }
 
            // ApiPassword (string) maxLength
            if(this.ApiPassword != null && this.ApiPassword.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ApiPassword, length must be less than 40.", new [] { "ApiPassword" });
            }

 
            yield break;
        }
    }

}
