/*
 * Tpay.com Technical Documentation
 *
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"bda5eda723bf1ae71a82e90a249803d3f852248d\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: pt@tpay.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SecuresaleResponse
    /// </summary>
    [DataContract]
    public partial class SecuresaleResponse :  IEquatable<SecuresaleResponse>, IValidatableObject
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Correct for value: correct
            /// </summary>
            [EnumMember(Value = "correct")]
            Correct = 1,

            /// <summary>
            /// Enum Declined for value: declined
            /// </summary>
            [EnumMember(Value = "declined")]
            Declined = 2

        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SecuresaleResponse" /> class.
        /// </summary>
        /// <param name="_3dsUrl">_3dsUrl.</param>
        /// <param name="result">result.</param>
        /// <param name="testMode">This parameter is present in response and included in sign calculation only when the merchant account is in test mode..</param>
        /// <param name="saleAuth">Transaction id in tpay.com system.</param>
        /// <param name="cliAuth">Client token.</param>
        /// <param name="currency">transaction currency in ISO numeric format (default to 985).</param>
        /// <param name="amount">transaction amount casted to float.</param>
        /// <param name="date">Date of payment.</param>
        /// <param name="status">status.</param>
        /// <param name="reason">Acquirer (Elavon / eService) rejection code - see \&quot;Card Payments Rejection Codes\&quot; for more details.</param>
        /// <param name="card">Card number last 4 digits - for example ****1234.</param>
        /// <param name="sign">sign is calculated from cryptographic hash function set in Merchant panel (default SHA-1) hash_alg(test_mode + sale_auth + cli_auth + card + currency + amount + date + status + verification code) .</param>
        /// <param name="errCode">errCode.</param>
        /// <param name="errDesc">Error code description if an error occurs or not present in response. - see \&quot;Card Payments Rejection Codes\&quot; for more details.</param>
        public SecuresaleResponse(string _3dsUrl = default(string), Result result = default(Result), string testMode = default(string), string saleAuth = default(string), string cliAuth = default(string), int currency = 985, decimal amount = default(decimal), string date = default(string), StatusEnum? status = default(StatusEnum?), string reason = default(string), string card = default(string), string sign = default(string), CardsErrCode errCode = default(CardsErrCode), string errDesc = default(string))
        {
            this._3dsUrl = _3dsUrl;
            this.Result = result;
            this.TestMode = testMode;
            this.SaleAuth = saleAuth;
            this.CliAuth = cliAuth;
            // use default value if no "currency" provided
            if (currency == null)
            {
                this.Currency = 985;
            }
            else
            {
                this.Currency = currency;
            }
            this.Amount = amount;
            this.Date = date;
            this.Status = status;
            this.Reason = reason;
            this.Card = card;
            this.Sign = sign;
            this.ErrCode = errCode;
            this.ErrDesc = errDesc;
        }

        /// <summary>
        /// Gets or Sets _3dsUrl
        /// </summary>
        [DataMember(Name="3ds_url", EmitDefaultValue=false)]
        public string _3dsUrl { get; set; }

        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [DataMember(Name="result", EmitDefaultValue=false)]
        public Result Result { get; set; }

        /// <summary>
        /// This parameter is present in response and included in sign calculation only when the merchant account is in test mode.
        /// </summary>
        /// <value>This parameter is present in response and included in sign calculation only when the merchant account is in test mode.</value>
        [DataMember(Name="test_mode", EmitDefaultValue=false)]
        public string TestMode { get; set; }

        /// <summary>
        /// Transaction id in tpay.com system
        /// </summary>
        /// <value>Transaction id in tpay.com system</value>
        [DataMember(Name="sale_auth", EmitDefaultValue=false)]
        public string SaleAuth { get; set; }

        /// <summary>
        /// Client token
        /// </summary>
        /// <value>Client token</value>
        [DataMember(Name="cli_auth", EmitDefaultValue=false)]
        public string CliAuth { get; set; }

        /// <summary>
        /// transaction currency in ISO numeric format
        /// </summary>
        /// <value>transaction currency in ISO numeric format</value>
        [DataMember(Name="currency", EmitDefaultValue=false)]
        public int Currency { get; set; }

        /// <summary>
        /// transaction amount casted to float
        /// </summary>
        /// <value>transaction amount casted to float</value>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Date of payment
        /// </summary>
        /// <value>Date of payment</value>
        [DataMember(Name="date", EmitDefaultValue=false)]
        public string Date { get; set; }


        /// <summary>
        /// Acquirer (Elavon / eService) rejection code - see \&quot;Card Payments Rejection Codes\&quot; for more details
        /// </summary>
        /// <value>Acquirer (Elavon / eService) rejection code - see \&quot;Card Payments Rejection Codes\&quot; for more details</value>
        [DataMember(Name="reason", EmitDefaultValue=false)]
        public string Reason { get; set; }

        /// <summary>
        /// Card number last 4 digits - for example ****1234
        /// </summary>
        /// <value>Card number last 4 digits - for example ****1234</value>
        [DataMember(Name="card", EmitDefaultValue=false)]
        public string Card { get; set; }

        /// <summary>
        /// sign is calculated from cryptographic hash function set in Merchant panel (default SHA-1) hash_alg(test_mode + sale_auth + cli_auth + card + currency + amount + date + status + verification code) 
        /// </summary>
        /// <value>sign is calculated from cryptographic hash function set in Merchant panel (default SHA-1) hash_alg(test_mode + sale_auth + cli_auth + card + currency + amount + date + status + verification code) </value>
        [DataMember(Name="sign", EmitDefaultValue=false)]
        public string Sign { get; set; }

        /// <summary>
        /// Gets or Sets ErrCode
        /// </summary>
        [DataMember(Name="err_code", EmitDefaultValue=false)]
        public CardsErrCode ErrCode { get; set; }

        /// <summary>
        /// Error code description if an error occurs or not present in response. - see \&quot;Card Payments Rejection Codes\&quot; for more details
        /// </summary>
        /// <value>Error code description if an error occurs or not present in response. - see \&quot;Card Payments Rejection Codes\&quot; for more details</value>
        [DataMember(Name="err_desc", EmitDefaultValue=false)]
        public string ErrDesc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SecuresaleResponse {\n");
            sb.Append("  _3dsUrl: ").Append(_3dsUrl).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  TestMode: ").Append(TestMode).Append("\n");
            sb.Append("  SaleAuth: ").Append(SaleAuth).Append("\n");
            sb.Append("  CliAuth: ").Append(CliAuth).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Card: ").Append(Card).Append("\n");
            sb.Append("  Sign: ").Append(Sign).Append("\n");
            sb.Append("  ErrCode: ").Append(ErrCode).Append("\n");
            sb.Append("  ErrDesc: ").Append(ErrDesc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SecuresaleResponse);
        }

        /// <summary>
        /// Returns true if SecuresaleResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of SecuresaleResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SecuresaleResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._3dsUrl == input._3dsUrl ||
                    (this._3dsUrl != null &&
                    this._3dsUrl.Equals(input._3dsUrl))
                ) && 
                (
                    this.Result == input.Result ||
                    (this.Result != null &&
                    this.Result.Equals(input.Result))
                ) && 
                (
                    this.TestMode == input.TestMode ||
                    (this.TestMode != null &&
                    this.TestMode.Equals(input.TestMode))
                ) && 
                (
                    this.SaleAuth == input.SaleAuth ||
                    (this.SaleAuth != null &&
                    this.SaleAuth.Equals(input.SaleAuth))
                ) && 
                (
                    this.CliAuth == input.CliAuth ||
                    (this.CliAuth != null &&
                    this.CliAuth.Equals(input.CliAuth))
                ) && 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.Date == input.Date ||
                    (this.Date != null &&
                    this.Date.Equals(input.Date))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Reason == input.Reason ||
                    (this.Reason != null &&
                    this.Reason.Equals(input.Reason))
                ) && 
                (
                    this.Card == input.Card ||
                    (this.Card != null &&
                    this.Card.Equals(input.Card))
                ) && 
                (
                    this.Sign == input.Sign ||
                    (this.Sign != null &&
                    this.Sign.Equals(input.Sign))
                ) && 
                (
                    this.ErrCode == input.ErrCode ||
                    (this.ErrCode != null &&
                    this.ErrCode.Equals(input.ErrCode))
                ) && 
                (
                    this.ErrDesc == input.ErrDesc ||
                    (this.ErrDesc != null &&
                    this.ErrDesc.Equals(input.ErrDesc))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._3dsUrl != null)
                    hashCode = hashCode * 59 + this._3dsUrl.GetHashCode();
                if (this.Result != null)
                    hashCode = hashCode * 59 + this.Result.GetHashCode();
                if (this.TestMode != null)
                    hashCode = hashCode * 59 + this.TestMode.GetHashCode();
                if (this.SaleAuth != null)
                    hashCode = hashCode * 59 + this.SaleAuth.GetHashCode();
                if (this.CliAuth != null)
                    hashCode = hashCode * 59 + this.CliAuth.GetHashCode();
                if (this.Currency != null)
                    hashCode = hashCode * 59 + this.Currency.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.Date != null)
                    hashCode = hashCode * 59 + this.Date.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Reason != null)
                    hashCode = hashCode * 59 + this.Reason.GetHashCode();
                if (this.Card != null)
                    hashCode = hashCode * 59 + this.Card.GetHashCode();
                if (this.Sign != null)
                    hashCode = hashCode * 59 + this.Sign.GetHashCode();
                if (this.ErrCode != null)
                    hashCode = hashCode * 59 + this.ErrCode.GetHashCode();
                if (this.ErrDesc != null)
                    hashCode = hashCode * 59 + this.ErrDesc.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SaleAuth (string) maxLength
            if(this.SaleAuth != null && this.SaleAuth.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SaleAuth, length must be less than 40.", new [] { "SaleAuth" });
            }

            // SaleAuth (string) minLength
            if(this.SaleAuth != null && this.SaleAuth.Length < 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SaleAuth, length must be greater than 40.", new [] { "SaleAuth" });
            }
 
            // CliAuth (string) maxLength
            if(this.CliAuth != null && this.CliAuth.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CliAuth, length must be less than 40.", new [] { "CliAuth" });
            }

            // CliAuth (string) minLength
            if(this.CliAuth != null && this.CliAuth.Length < 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CliAuth, length must be greater than 40.", new [] { "CliAuth" });
            }
 

 

 
            // Amount (decimal) minimum
            if(this.Amount < (decimal)0.1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Amount, must be a value greater than or equal to 0.1.", new [] { "Amount" });
            }


 
            // Date (string) pattern
            Regex regexDate = new Regex(@"YYYY-MM-DD HH:mm:ss", RegexOptions.CultureInvariant);
            if (false == regexDate.Match(this.Date).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Date, must match a pattern of " + regexDate, new [] { "Date" });
            }

            // Sign (string) maxLength
            if(this.Sign != null && this.Sign.Length > 128)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Sign, length must be less than 128.", new [] { "Sign" });
            }

            // Sign (string) minLength
            if(this.Sign != null && this.Sign.Length < 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Sign, length must be greater than 40.", new [] { "Sign" });
            }
 
            yield break;
        }
    }

}
