/*
 * Tpay.com Technical Documentation
 *
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"bda5eda723bf1ae71a82e90a249803d3f852248d\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: pt@tpay.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// VcPrepareFields
    /// </summary>
    [DataContract]
    public partial class VcPrepareFields :  IEquatable<VcPrepareFields>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VcPrepareFields" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VcPrepareFields() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VcPrepareFields" /> class.
        /// </summary>
        /// <param name="apiPassword">API password. (required).</param>
        /// <param name="callId">Visa Checkout Call Id (required).</param>
        /// <param name="language">language.</param>
        /// <param name="sign">Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): hash_alg (method + call_id + language + verification code) where + means concatenation. (required).</param>
        public VcPrepareFields(string apiPassword = default(string), string callId = default(string), Language language = default(Language), string sign = default(string))
        {
            // to ensure "apiPassword" is required (not null)
            if (apiPassword == null)
            {
                throw new InvalidDataException("apiPassword is a required property for VcPrepareFields and cannot be null");
            }
            else
            {
                this.ApiPassword = apiPassword;
            }

            // to ensure "callId" is required (not null)
            if (callId == null)
            {
                throw new InvalidDataException("callId is a required property for VcPrepareFields and cannot be null");
            }
            else
            {
                this.CallId = callId;
            }

            // to ensure "sign" is required (not null)
            if (sign == null)
            {
                throw new InvalidDataException("sign is a required property for VcPrepareFields and cannot be null");
            }
            else
            {
                this.Sign = sign;
            }

            this.Language = language;
        }

        /// <summary>
        /// API password.
        /// </summary>
        /// <value>API password.</value>
        [DataMember(Name="api_password", EmitDefaultValue=true)]
        public string ApiPassword { get; set; }

        /// <summary>
        /// Visa Checkout Call Id
        /// </summary>
        /// <value>Visa Checkout Call Id</value>
        [DataMember(Name="call_id", EmitDefaultValue=true)]
        public string CallId { get; set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [DataMember(Name="language", EmitDefaultValue=false)]
        public Language Language { get; set; }

        /// <summary>
        /// Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): hash_alg (method + call_id + language + verification code) where + means concatenation.
        /// </summary>
        /// <value>Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): hash_alg (method + call_id + language + verification code) where + means concatenation.</value>
        [DataMember(Name="sign", EmitDefaultValue=true)]
        public string Sign { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VcPrepareFields {\n");
            sb.Append("  ApiPassword: ").Append(ApiPassword).Append("\n");
            sb.Append("  CallId: ").Append(CallId).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Sign: ").Append(Sign).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VcPrepareFields);
        }

        /// <summary>
        /// Returns true if VcPrepareFields instances are equal
        /// </summary>
        /// <param name="input">Instance of VcPrepareFields to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VcPrepareFields input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ApiPassword == input.ApiPassword ||
                    (this.ApiPassword != null &&
                    this.ApiPassword.Equals(input.ApiPassword))
                ) && 
                (
                    this.CallId == input.CallId ||
                    (this.CallId != null &&
                    this.CallId.Equals(input.CallId))
                ) && 
                (
                    this.Language == input.Language ||
                    (this.Language != null &&
                    this.Language.Equals(input.Language))
                ) && 
                (
                    this.Sign == input.Sign ||
                    (this.Sign != null &&
                    this.Sign.Equals(input.Sign))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ApiPassword != null)
                    hashCode = hashCode * 59 + this.ApiPassword.GetHashCode();
                if (this.CallId != null)
                    hashCode = hashCode * 59 + this.CallId.GetHashCode();
                if (this.Language != null)
                    hashCode = hashCode * 59 + this.Language.GetHashCode();
                if (this.Sign != null)
                    hashCode = hashCode * 59 + this.Sign.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ApiPassword (string) maxLength
            if(this.ApiPassword != null && this.ApiPassword.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ApiPassword, length must be less than 40.", new [] { "ApiPassword" });
            }

 
            yield break;
        }
    }

}
