// <auto-generated />
namespace Skilldemy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CourseandTagmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CourseandTagmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "202206301547542_Course and Tag models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
